version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    networks:
      - mysqlnetwork
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'khaddemApp'
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword

  kaddem:
    build:
      context: ,
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - mysqlnetwork
    ports:
      - "8089:8089"



networks:
  mysqlnetwork: